trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ls $(System.DefaultWorkingDirectory)
  displayName: 'Print Working Directory'

- task: CmdLine@2
  displayName: 'Build Image'
  inputs:
    script: 'docker build -t cwe-toastmasters . --build-arg SENDER_EMAIL=$(SENDER_EMAIL) --build-arg RECEIVER_EMAIL=$(RECEIVER_EMAIL) --build-arg EMAIL_PASSWORD=$(EMAIL_PASSWORD)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: ECRPushImage@1
  displayName: 'Push to ECR'
  inputs:
    awsCredentials: 'azure_pipeline'
    regionName: 'us-east-2'
    imageSource: 'imagename'
    sourceImageName: 'cwe-toastmasters'
    repositoryName: 'cwe-toastmasters'
    logResponse: true
